version: "3.2"
services:
  database:
    environment:
      - MYSQL_DATABASE=yejeongdo
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_ROOT_HOST=%
  application:
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/yejeongdo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234